### ISSUE TITLE
Applying to own data

### ISSUE THREAD

**Issue by andrewjmc** [lakerwsl/MsRDB-Manuscript-Code#1]
Hello,

Grateful for your advice on how MsRDB would be applied to other data, especially where a tree structure is already available (e.g. metagenomic data with relative abundances of species and an accompanying phylogeny).

Thanks,

Andrew

**Comment by lakerwsl** [comment]
Hi Andrew,

Thanks for the email. The input of MsRDB is a distance matrix. If you already have a phylogenetic tree, you may want to convert it to a distance matrix. For example, we can measure the distance between pairs of nodes, i.e., patristic distance or the number of nodes intervening between the pair. One option is to call distNodes() in RRphylo package (although I haven't used it before). Hope it is helpful. 

Best,
Shulei
